name: "Build LLVM"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Git tag for the release.'
        required: true
        type: string

jobs:
  build_llvm:
    name: Build LLVM
    strategy:
      matrix:
        # os: [ubuntu-20.04, macos-12, windows-2019]
        os: [ubuntu-20.04, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - if: contains(matrix.os, 'ubuntu')
        run: "sudo apt update && sudo apt install -y ninja-build"
      - if: contains(matrix.os, 'macos')
        run: "brew install ninja"
      # Build and package LLVM.
      - run: "./build-llvm-libs.sh llvm-static-libs-${{ matrix.os }}.tar.gz"
      - uses: actions/upload-artifact@v4
        with:
          name: llvm-static-libs-${{ matrix.os }}
          path: llvm-static-libs-${{ matrix.os }}.tar.gz

  create_release:
    name: Create release
    runs-on: ubuntu-latest
    needs: [build_llvm]
    permissions:
      contents: write # for creating releases
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: llvm-static-libs-*
          merge-multiple: true
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: LLVM tooling libraries ${{ inputs.tag }}
          tag_name: ${{ inputs.tag }}
          files: llvm-static-libs-*
          fail_on_unmatched_files: true
